apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sp-vilkarsproving-opprydding-dev
  namespace: tbd
  labels:
    team: tbd
    dbPolicyUser: sp-vilkarsproving-opprydding-dev
spec:
  port: 8080
  startup:
    path: isready
    initialDelay: 20
    periodSeconds: 5
    failureThreshold: 9
  liveness:
    path: isalive
  readiness:
    path: isready
  preStopHook:
    http:
      path: /stop
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
        - id: team_logs
  resources:
    requests:
      cpu: 50m
      memory: 320Mi
    limits:
      memory: 512Mi
  replicas:
    min: 1
    max: 1
  strategy:
    type: Recreate
  kafka:
    pool: nav-dev
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
  prometheus:
    enabled: true
    path: /metrics
  envFrom:
    # Denne finner du ved å se på environment variables til "hovedappen", finn miljøvariabler knyttet til den ekstra brukeren du har laget.
    # Deretter ser du på secret'en disse er hentet fra
    - secret: google-sql-sp-vilkarsproving-sp-vilkarsproving-sp-vilk-886117fc
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-sp-vilkarsproving-opprydding-dev-v1
    - name: KAFKA_RESET_POLICY
      value: latest
    - name: DATABASE_REGION
      value: europe-north1
    - name: DATABASE_INSTANCE
      value: sp-vilkarsproving
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
