[versions]
flyway = "13.3.0"
# Må følge Kotlin-versjonen som sas-kotlin-pluginen bruker
kotlin = "2.4.10"
ktor = "3.5.2"
tbd-libs = "20260823.1727"
rapidsAndRivers = "2026071513121784113927"
sasGradlePlugins = "20260807.0944"
testcontainers = "2.0.5"

[libraries]
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
hikaricp = "com.zaxxer:HikariCP:7.1.0"
cloud-sql-postgres-socket-factory = "com.google.cloud.sql:postgres-socket-factory:1.29.0"
kotliquery = "com.github.seratch:kotliquery:1.9.1"
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
tbd-libs-speil-backend-app = {module = "com.github.navikt.tbd-libs:speil-backend-app", version.ref = "tbd-libs"}
tbd-libs-access-token-provider-texas = {module = "com.github.navikt.tbd-libs:access-token-provider-texas", version.ref = "tbd-libs"}
postgresql = "org.postgresql:postgresql:42.7.13"
rapids-and-rivers = {module = "com.github.navikt:rapids-and-rivers", version.ref = "rapidsAndRivers"}
rapids-and-rivers-test = {module = "com.github.navikt.rapids-and-rivers:rapids-and-rivers-test", version.ref = "rapidsAndRivers"}
testcontainers-postgres = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testcontainers" }
wiremock = "org.wiremock:wiremock-jetty12:3.13.2"


[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sas-deployable = { id = "no.nav.helse.sas.sas-deployable", version.ref = "sasGradlePlugins" }
sas-kotlin = { id = "no.nav.helse.sas.sas-kotlin", version.ref = "sasGradlePlugins" }
sas-root = { id = "no.nav.helse.sas.sas-root", version.ref = "sasGradlePlugins" }
